# Change these first
owner: trentwiles # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Main Website
    url: https://www.trentwiles.com
  - name: BART API
    url: https://bart.trentwil.es
  - name: Internal Image Endpoint
    url: https://api.trentwil.es

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.trentwiles.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Trent Wiles Status
  introTitle: "Service Status"
  introMessage: 
  navbar:
    - title: Trent Wiles Status
      href: /
    - title: Return Home
      href: https://www.trentwiles.com/?utm_source=status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
